### ISSUE TITLE
BGW restarts when MQTT broker is not available

### ISSUE THREAD

**Issue by farshidtz** [linksmart/border-gateway#42]
The BGW is killed internally when a proxied MQTT broker stops responding. 

Here are the BGW logs:
```
Starting LinkSmart Border Gateway...
bgw-http-proxy
Started service bgw-http-proxy with debug port 9227
bgw-mqtt-proxy
Started service bgw-mqtt-proxy with debug port 9228
bgw-websocket-proxy
Started service bgw-websocket-proxy with debug port 9229
bgw-auth-service
Started service bgw-auth-service with debug port 9230
Debugger listening on ws://0.0.0.0:9228/f573624a-0017-466b-a326-6b9c618c49c1
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://0.0.0.0:9229/a7e2eb2b-cbe2-450b-ad00-4c921e260d20
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://0.0.0.0:9227/a613962c-cbff-4422-9faa-6aaf3d1641f4
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://0.0.0.0:9230/bee00745-ca7f-40b9-baef-a102411bc0c5
For help, see: https://nodejs.org/en/docs/inspector
2019-09-23T14:18:06.522Z [websocket-proxy] debug: Creating server 127.0.0.1 9001 {}
2019-09-23T14:18:06.558Z [websocket-proxy] debug: server event listening {}
2019-09-23T14:18:06.680Z [mqtt-proxy] info: mqtt-proxy listening on 0.0.0.0:1883 {}
2019-09-23T14:18:06.738Z [http-proxy] info: http-proxy listening on 0.0.0.0:80 {}
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND mosquitto mosquitto:1883
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
./bgw.sh: line 49:     6 Killed                  run_inspect_service "$var" $debugPort
./bgw.sh: line 49:     7 Killed                  run_inspect_service "$var" $debugPort
./bgw.sh: line 49:     8 Killed                  run_inspect_service "$var" $debugPort
./bgw.sh: line 49:    10 Killed                  run_inspect_service "$var" $debugPort
```

**Comment by janniswarnat** [comment]
Thanks for opening the issue. This has been fixed a few months ago, so in the current version of Border Gateway this error should not come up.
